trigger: none

variables:
  - template: ./config-infra.yml
  - name: WORKSPACE_SKU # https://docs.microsoft.com/en-us/azure/machine-learning/overview-what-is-azure-ml#sku
    value: basic

pool:
  vmImage: $(ap_vm_image)

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(ado_service_connection_rg)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(resource_group)"
      location: $(location)
      templateLocation: "Linked artifact"
      csmFile: "./iac-pipeline/cloud-environment.json"
      overrideParameters: "-baseName $(namespace) -location $(location) -workspace $(aml_workspace) -sku $(WORKSPACE_SKU)"
      deploymentMode: "Incremental"
    displayName: "Deploy MLOps resources to Azure"
